-- AlterTable
ALTER TABLE "CreatorProfile" ADD COLUMN IF NOT EXISTS "videoCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CreatorProfile" ADD COLUMN IF NOT EXISTS "viewCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CreatorProfile" ADD COLUMN IF NOT EXISTS "posts7d" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CreatorProfile" ADD COLUMN IF NOT EXISTS "posts90d" INTEGER NOT NULL DEFAULT 0;
