import { Link } from "react-router-dom";

const TRUSTED = [
  "BlogSEO",
  "Attio",
  "Lemlist",
  "Waalaxy",
  "Phantombuster",
  "Brevo",
] as const;

const STEPS = [
  {
    title: "Find creators",
    body: "Discover B2B voices your buyers already trust, ranked by audience fit—not vanity follower counts.",
  },
  {
    title: "Build brief",
    body: "Define objectives, key messages, guidelines, and tracking links in minutes.",
  },
  {
    title: "Manage collaborations",
    body: "Move every deal from draft to scheduled to live in one shared workspace.",
  },
  {
    title: "Track results",
    body: "Connect posts to views, clicks, leads, and attributed pipeline.",
  },
  {
    title: "Pay creators",
    body: "Approve content and let Naano handle contracts, invoices, and payouts.",
  },
] as const;

export function HomePage() {
  return (
    <>
      <section className="mx-auto max-w-6xl px-4 pb-16 pt-14 sm:px-6 sm:pb-24 sm:pt-20">
        <p className="mb-4 text-4xl font-extrabold tracking-tight text-ink sm:text-5xl">
          naano
        </p>
        <h1 className="max-w-3xl text-3xl font-extrabold leading-tight tracking-tight text-ink sm:text-5xl">
          The B2B LinkedIn Creator Marketplace.
        </h1>
        <p className="mt-5 max-w-2xl text-base leading-relaxed text-muted sm:text-lg">
          Find the creators your buyers already trust, launch campaigns in days,
          and track the clicks, leads and pipeline generated by every post.
        </p>
        <div className="mt-8 flex flex-wrap gap-3">
          <Link to="/register?role=saas" className="btn-navy">
            Launch a campaign
          </Link>
          <a href="#how-it-works" className="btn-ghost">
            See how Naano works
          </a>
        </div>
      </section>

      <section className="border-y border-sky-deep/40 bg-surface/50 py-8">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <p className="mb-5 text-center text-xs font-semibold uppercase tracking-[0.14em] text-muted">
            Trusted by modern B2B teams
          </p>
          <ul className="flex flex-wrap items-center justify-center gap-x-8 gap-y-3">
            {TRUSTED.map((name) => (
              <li
                key={name}
                className="text-sm font-semibold tracking-wide text-ink/45 sm:text-base"
              >
                {name}
              </li>
            ))}
          </ul>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20">
        <p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted">
          The Naano creator marketplace
        </p>
        <h2 className="mt-3 max-w-2xl text-2xl font-extrabold tracking-tight text-ink sm:text-4xl">
          Work with all the best creators.
        </h2>
        <p className="mt-4 max-w-2xl text-base leading-relaxed text-muted sm:text-lg">
          Find the right B2B voices, compare their audience fit, and book every
          collaboration from one place. Vertical fit beats raw follower count.
        </p>
        <div className="mt-10 grid gap-4 sm:grid-cols-3">
          {[
            { label: "3,000+", detail: "vetted creators ready to collaborate" },
            { label: "100+", detail: "countries with local B2B expertise" },
            { label: "Fit-first", detail: "audience match before follower count" },
          ].map((stat) => (
            <div
              key={stat.label}
              className="rounded-2xl border border-sky-deep/60 bg-surface/70 px-5 py-6"
            >
              <p className="text-2xl font-extrabold text-ink">{stat.label}</p>
              <p className="mt-2 text-sm text-muted">{stat.detail}</p>
            </div>
          ))}
        </div>
      </section>

      <section
        id="how-it-works"
        className="scroll-mt-20 border-y border-sky-deep/40 bg-surface/40 py-16 sm:py-20"
      >
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted">
            One platform, from brief to results
          </p>
          <h2 className="mt-3 max-w-2xl text-2xl font-extrabold tracking-tight text-ink sm:text-4xl">
            Run creator campaigns from one place.
          </h2>
          <ol className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-5">
            {STEPS.map((step, index) => (
              <li key={step.title} className="flex flex-col gap-2">
                <span className="text-xs font-bold text-sky-deep">
                  {String(index + 1).padStart(2, "0")}
                </span>
                <h3 className="text-base font-bold text-ink">{step.title}</h3>
                <p className="text-sm leading-relaxed text-muted">{step.body}</p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20">
        <h2 className="text-2xl font-extrabold tracking-tight text-ink sm:text-4xl">
          Pricing.
        </h2>
        <p className="mt-3 max-w-xl text-muted">
          Start free, or hand the campaign to Naano. Creator spend is always
          separate from the plan fee.
        </p>
        <div className="mt-8 grid gap-4 sm:grid-cols-2">
          <div className="rounded-2xl border border-sky-deep/60 bg-surface/80 p-6">
            <p className="text-sm font-semibold text-muted">Self-Serve</p>
            <p className="mt-2 text-3xl font-extrabold text-ink">
              €0
              <span className="text-base font-semibold text-muted"> / mo</span>
            </p>
            <p className="mt-3 text-sm text-muted">
              Full marketplace access. You book creators at their fixed post
              rates.
            </p>
          </div>
          <div className="rounded-2xl border border-navy/20 bg-navy p-6 text-white">
            <p className="text-sm font-semibold text-white/70">Managed</p>
            <p className="mt-2 text-3xl font-extrabold">
              €700
              <span className="text-base font-semibold text-white/70"> / mo</span>
            </p>
            <p className="mt-3 text-sm text-white/75">
              Naano sources creators, writes briefs, and runs campaigns end to
              end.
            </p>
          </div>
        </div>
        <Link
          to="/pricing"
          className="mt-6 inline-flex text-sm font-semibold text-navy no-underline hover:underline"
        >
          Compare plans →
        </Link>
      </section>

      <section className="border-t border-sky-deep/40 bg-surface/50 py-16 sm:py-20">
        <div className="mx-auto max-w-6xl px-4 text-center sm:px-6">
          <h2 className="text-2xl font-extrabold tracking-tight text-ink sm:text-4xl">
            Your next creator campaign starts here.
          </h2>
          <p className="mx-auto mt-4 max-w-xl text-muted">
            Launch on Self-Serve today, or talk to the team when you want
            campaigns run for you.
          </p>
          <div className="mt-8 flex flex-wrap justify-center gap-3">
            <Link to="/register?role=saas" className="btn-navy">
              Start for free
            </Link>
            <Link to="/pricing" className="btn-ghost">
              View pricing
            </Link>
          </div>
        </div>
      </section>
    </>
  );
}
